### ISSUE TITLE
bypass CF请教

### ISSUE THREAD

**Issue by destinokm** [Lqlsoftware/avutil#1]
请问一下大佬是怎么过CF的，看源码了解到是通过代理服务器？可以解释说明一下吗，不胜感激！

**Comment by Lqlsoftware** [comment]
Emmmm，其实是这样，Library这边主站对国内IP是CF保护的，但是镜像站没有保护，所以问题变成了如何拿到镜像站的入口。
Sorry，希望Bypass CF的话还是推荐用[Selenium WebDriver](https://www.selenium.dev/selenium/docs/api/py/) + Headless Chrome（非常简单），但是对于这个项目来说，我希望能够尽可能减少依赖。

**Comment by destinokm** [comment]
哦哦, 原来是用这种方式解决的吗，实际上是绕开了主站的CF保护。Emm, 能这样解决确实没必要增加依赖. Selenium WebDriver + Headless Chrome的方式是吗, 谢谢提醒哈！

**Comment by Lqlsoftware** [comment]
嗯嗯，Selenium是真的去打开浏览器模拟行为，所以CF没法判别
